services:
  db:
    image: postgres:16-alpine
    container_name: transitops-db
    environment:
      POSTGRES_USER: transitops_admin
      POSTGRES_PASSWORD: internal_secure_pass
      POSTGRES_DB: transitops_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transitops_admin -d transitops_prod"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: transitops-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: transitops-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://transitops_admin:internal_secure_pass@db:5432/transitops_prod
      - SECRET_KEY=9a2f7c320d3f848529b4e5414d6438a9d18e225bb1536b9e28f3bb2511470e9a
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=false
      - MINIO_BUCKET=transitops-documents
      - MINIO_EXTERNAL_URL=http://localhost:9000
      - TOLLGURU_API_KEY=tg_4FE916BF3F704B51822BEE22A26A62BA
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: transitops-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data: